task:
  container:
    cpu: 8
    memory: 8G
    image: python:latest
  timeout_in: 120m
  pip_cache:
    folder: ~/

  build_script:
# Install dependency
    - apt-get update
    - apt-get -qq install magic-wormhole software-properties-common
    - add-apt-repository ppa:jon-hedgerows/get-iplayer
    - echo "deb http://www.deb-multimedia.org stretch main non-free" >> /etc/apt/sources.list
    - apt-get update -oAcquire::AllowInsecureRepositories=true
    - apt-get -qq  --allow-unauthenticated install -y deb-multimedia-keyring
    - apt-get update
    - apt-get dist-upgrade
    - apt-get -qq --allow-unauthenticated install get-iplayer ffmpeg

#    - pip3 install --upgrade youtube-dl
    - cd ~/
#    - rm -R * #output.mkv | echo ""

#    - youtube-dl https://www.bbc.co.uk/iplayer/episode/m0002fq1/hospital-series-4-episode-5 --add-metadata --write-sub --convert-subs srt --embed-subs --proxy http://62.7.85.234:8080/ -f "[height >= 480][tbr<=2380]" --recode-video mkv --postprocessor-args "-crf 25 -tune film" -o "output.%(ext)s"
    #- ffmpeg -i *.mp4 -crf 25 output.mp4

#    - get_iplayer --proxy=http://62.7.85.234:8080/ --get https://www.bbc.co.uk/iplayer/episode/m0002fq1/hospital-series-4-episode-5 --metadata --thumbnail --subtitles --tvmode=hlshd,tvbetter --fps25 --command-tv='ffmpeg -i "<filename>" -i *.srt -c:v libx264 -crf 25 -tune film -preset veryslow -b:a 192k -scodec srt -y output.mkv'
    - ffmpeg -i *.mp4 -i *.srt -c:v libx264 -crf 24.5 -tune film -preset veryslow -c:a aac -q:a 0.11 -aac_coder twoloop -scodec srt -y output.mkv
    - ls -l
    - curl --upload-file "./output.mkv" https://transfer.sh/HospitalS4E5.mkv 

  

   


