task:
  container:
    cpu: 8
    memory: 8G
    image: python:latest
  timeout_in: 120m
  pip_cache:
    folder: ~/

  build_script:
# Install dependency
    - apt-get update
    - apt-get -qq install ffmpeg

    - pip3 install --upgrade youtube-dl
    - cd ~/
    - youtube-dl https://www.bbc.co.uk/iplayer/episode/b0c1szk7/hospital-series-4-episode-4 --add-metadata --write-sub --convert-subs srt --embed-subs --proxy http://62.7.85.234:8080/ -f "[height >= 480][tbr<=2380]" --recode-video mkv --postprocessor-args "-crf 25 -tune film" -o "output.%(ext)s"
    #- ffmpeg -i *.mp4 -crf 25 output.mp4
    - ls -l
    - curl --upload-file "./output.mkv" https://transfer.sh/HospitalS4E4.mkv

   


