task:
  container:
    cpu: 8
    memory: 6G
    image: ubuntu:disco
  timeout_in: 120m
#  pip_cache:
#    folder: ~/

  build_script:
# Install dependency
    - apt-get update
    - apt-get -qq install software-properties-common
    - add-apt-repository ppa:jon-hedgerows/get-iplayer
    #- echo "deb http://ftp.us.debian.org/debian buster main" >> /etc/apt/sources.list
    - apt-get update
    - apt-get -qq --allow-unauthenticated -y install get-iplayer ffmpeg nodejs npm curl

#    - pip3 install --upgrade youtube-dl
    - cd ~/
    - npm install -g dat
    - curl https://getcroc.schollz.com | bash

#    - youtube-dl https://www.bbc.co.uk/iplayer/episode/m0002fq1/hospital-series-4-episode-5 --add-metadata --write-sub --convert-subs srt --embed-subs --proxy http://62.7.85.234:8080/ -f "[height >= 480][tbr<=2380]" --recode-video mkv --postprocessor-args "-crf 25 -tune film" -o "output.%(ext)s"
    #- ffmpeg -i *.mp4 -crf 25 output.mp4

    - get_iplayer --proxy=http://134.209.176.34:8080/ --subtitles --get http://www.bbc.co.uk/iplayer/episode/m0005wqx --metadata --thumbnail  --tvmode=hlshd,tvbetter --fps25 --command-tv='ffmpeg -i "<filename>" -i *.srt -map 0 -c:v libx264 -crf 24.4 -tune film -preset veryslow -c:a aac -scodec srt -y output.mkv'
    #- ffmpeg -i *.mp4 -i *.srt -map 0 -c:v libx264 -crf 24.4 -tune film -preset veryslow -c:a aac -scodec srt -y output.mkv
    - ls -l
    - curl --upload-file "./output.mkv" https://transfer.sh/SkyatNight.mkv; croc send output.mkv & dat share

  

   


