#sudo: required
dist: xenial
#services:
#  - docker
#before_install:
language: python
addons:
  apt:
    sources:
#    - mc3man-trusty-media
    packages:
    - ffmpeg
cache:
  directories:
    - ~/

script:
# Install dependency
#- sudo apt-get  -qq install -y dpkg
- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic main universe"
- sudo apt-get -qq update 
- sudo apt-get -qq install -y ffmpeg

- pyenv global 3.7.1
- pip3 install --upgrade youtube-dl
- cd ~/
- youtube-dl http://www.bbc.co.uk/iplayer/episode/m0005wqx --add-metadata --write-sub --convert-subs srt --embed-subs --proxy http://134.209.176.34:8080/ -f "[height >= 480][tbr<2100]"
# --recode-video mkv --postprocessor-args "-crf 27 -tune film"
- travis_wait 80 ffmpeg -i *.mp4 -i *.srt -map 0 -c:v libx264 -crf 24.4 -tune film -preset slow -c:a aac -scodec srt -y output.mkv
- ls -l
- curl --upload-file "./output.mkv" https://transfer.sh/SkyatNight.mkv; croc send output.mkv & dat share

#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key: ${KEY}
#  file_glob: true
#  file: "*.mp4"
#  on:
#  #  tags: true
#    all_branches: true


