#sudo: required
dist: trusty
#services:
#  - docker
#before_install:
language: None
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - flex
    - bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3
    - openjdk-7-jdk > /dev/null
script:
# Install dependency
#- sudo apt-get  -qq install -y dpkg
#- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic main"
#- sudo apt-get  -qq update 

- pip3 install --upgrade youtube-dl
- youtube-dl http://www.bbc.co.uk/iplayer/episode/b0c13s5n/hospital-series-4-episode-3 --add-metadata --write-sub --embed-subs --proxy http://62.7.85.234:8080/ -f "[height >= 480][tbr<2100]" --postprocessor-args "-crf 23 -tune film"

- ls -l

deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${KEY}
  file_glob: true
  file: "*.mp4"
  on:
  #  tags: true
    all_branches: true


