#sudo: required
dist: xenial
#services:
#  - docker
#before_install:
language: python
addons:
  apt:
    sources:
#    - mc3man-trusty-media
    packages:
    - ffmpeg

script:
# Install dependency
#- sudo apt-get  -qq install -y dpkg
#- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic main"
#- sudo apt-get  -qq update 

- pyenv global 3.7.1
- pip3 install --upgrade youtube-dl
- travis_wait 115 youtube-dl http://www.bbc.co.uk/iplayer/episode/b0c13s5n/hospital-series-4-episode-3 --add-metadata --write-sub --convert-subs srt --embed-subs --proxy http://62.7.85.234:8080/ -f "[height >= 480][tbr<2100]" --recode-video mkv --postprocessor-args "-crf 27 -tune film"

- ls -l

deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${KEY}
  file_glob: true
  file: "*.mp4"
  on:
  #  tags: true
    all_branches: true


